export const IS_COLUMN_HIDDEN = 'IS_COLUMN_HIDDEN';
export const UPDATE_API_DATA = 'UPDATE_API_DATA';
export const UPDATE_CELL_CHANGES = 'UPDATE_CELL_CHANGES';
export const UPDATE_CELL_INDEX = 'UPDATE_CELL_INDEX';
